// This file is auto-generated by @hey-api/openapi-ts

import type { GetPeakExpertPoolByIdResponse, GetPeakPoolByIdResponse } from './types.gen.js';

const peakPoolSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

export const getPeakPoolByIdResponseTransformer = async (data: any): Promise<GetPeakPoolByIdResponse> => {
    data = peakPoolSchemaResponseTransformer(data);
    return data;
};

const peakExpertPoolSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

export const getPeakExpertPoolByIdResponseTransformer = async (data: any): Promise<GetPeakExpertPoolByIdResponse> => {
    data = peakExpertPoolSchemaResponseTransformer(data);
    return data;
};
